.TH UDPREPLAY 1 2022-01-12 Linux
.SH NAME
udpReplay \- trasmit udp frame read from a pcap file
.SH SYNOPSIS
.B udpReplay
[-1|--step]
[-f|--flood]
[-d host|--dest host]
[--astx]
[--mttl ttlValue]
.IR pcapfile
.SH DESCRIPTION
.B udpReplay
get the udp packets in a pcap file and sends them as udp datagram
.SH OPTION
.TP
.BR -1 | --step
Send the datagram one by one waiting for input from console to send the next
.TP
.BR -f | --flood
Send the datagram as fast as it can
.TP
.BR --astx
Adjust the Asterix Time Of Day to reflect the time the message is sent
.TP
.BR -d\ host | --dest\ host
Send the datagram to the specified host. It this option is not present, data are sent to the original host as recorded in the pcap file
.TP
.BR --mttl\ ttlValue
Set the time to live for multicast packets to the value specified as argument. Otherwise is set to 1
.TP
.BR file
the file that contain the datagram to be sent. It should be in the pcap format
